// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageType } from "./MessageType";

export type AgentMessage = { timestamp: string, role: string, message_type: MessageType, content: string, };
