// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alert } from "./Alert";
import type { AlertSeverity } from "./AlertSeverity";

export type AlertPayload = { alert: Alert, severity: AlertSeverity, };
