// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskPriority } from "./TaskPriority";

export type CreateTaskRequest = { title: string, repo_url: string | null, repo_ref: string | null, description: string, base_branch: string | null, target_branch: string | null, priority: TaskPriority | null, ssh_key: string | null, ssh_key_ref: string | null, max_execution_time: bigint | null, project_id?: string, required_labels: { [key in string]: string }, };
