// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageType = "Thought" | "Text" | "ToolCall" | "ToolResult" | "Image" | "Resource" | "Plan" | "UserMessage";
