// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkerEvent } from "./WorkerEvent";

export type PushEventsRequest = { token: string, events: Array<WorkerEvent>, };
