// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkerCapabilities } from "./WorkerCapabilities";

export type RegisterWorkerRequest = { name: string, capabilities: WorkerCapabilities, max_concurrent: number, };
