// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeedbackType } from "./FeedbackType";

export type SubmitFeedbackRequest = { feedback_type: FeedbackType, message: string, };
