// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskAssignment = { id: string, repo_url: string, description: string, base_branch: string, target_branch: string, ssh_key: string, max_execution_time: bigint, };
