// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskPriority } from "./TaskPriority";
import type { TaskStatus } from "./TaskStatus";

export type Task = { id: string, title: string, repo_url: string, description: string, base_branch: string, target_branch: string, status: TaskStatus, priority: TaskPriority, created_at: string, updated_at: string, claimed_by?: string, ssh_key: string, max_execution_time: number, required_labels: { [key in string]: string }, };
