// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Task } from "./Task";

export type TaskListResponse = { tasks: Array<Task>, total: bigint, next_cursor: string | null, has_more: boolean, };
