// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoConfig } from "./RepoConfig";
import type { SshKeyConfig } from "./SshKeyConfig";

export type UpdateProjectRequest = { name: string | null, repos: Array<RepoConfig> | null, ssh_keys: Array<SshKeyConfig> | null, parent_id?: string | null, };
