// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HumanFeedback } from "./HumanFeedback";
import type { TaskAssignment } from "./TaskAssignment";

export type WorkerInstruction = { "type": "assign_task", task: TaskAssignment, } | { "type": "cancel_task", task_id: string, reason: string, } | { "type": "update_task", task_id: string, instruction: string, } | { "type": "approve_iteration", task_id: string, } | { "type": "provide_feedback", task_id: string, feedback: HumanFeedback, } | { "type": "abort_task", task_id: string, reason: string, };
