// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkerStatus } from "./WorkerStatus";

export type WorkerSummary = { id: string, name: string, status: WorkerStatus, last_heartbeat: string, current_task_count: number, };
